### ISSUE TITLE
Add suport to ANSI Colors and a more verbose initialization

### ISSUE THREAD

**Issue by Braayy** [Elytra-Server/Elytra#5]
My suggestion is to add a support to ANSI to colorize a little bit of the terminal when printing the informations.

[Jansi](https://github.com/fusesource/jansi) is a lib with this purpose.

By now the INB isn't printing much. It will be good if a more verbose info gets printed, like the version/versions supported, the host:port where the server was bound to and so on, to help the user knows what is happening.

**Comment by TommyAlmeida** [comment]
Already started to implement logging, ANSI colors are already enumerated but not implemented yet. #5ec42a0d049e636930609e7bff3af699726fec10

**Comment by Braayy** [comment]
Something that i noticed is the ansi escape codes does not work with windows command prompt, this was the reason why i mencioned Jansi.

**Comment by TommyAlmeida** [comment]
Hmm, ok didn't know that to be honest. Gonna check that Jansi.

**Comment by JPereirax** [comment]
We still have something related to that today, thanks for the comment. 💪
